ignoredBuiltDependencies:
  - nx

onlyBuiltDependencies:
  - esbuild

packages:
  - '@watsonserve/*'

allowBuilds:
  core-js: false
  electron: false
  esbuild: true

minimumReleaseAgeExclude:
  - '@watsonserve/ui@0.0.8'
